import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import rawApi from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  manual: [
    {
      type: "category",
      label: "Manual",
      className: "sidebar-breadcrumb-only",
      collapsible: false,
      link: {
        type: "doc",
        id: "manual/index",
      },
      items: [{ type: "autogenerated", dirName: "manual" }],
    },
  ],

  developers: [
    {
      type: "category",
      label: "Developers",
      className: "sidebar-breadcrumb-only",
      collapsible: false,
      link: {
        type: "doc",
        id: "devs/index",
      },
      items: [{ type: "autogenerated", dirName: "devs" }],
    },
  ],

  api: [
    {
      type: "category",
      label: "API",
      className: "sidebar-breadcrumb-only",
      collapsible: false,
      link: {
        type: "doc",
        id: "api/xenforo-api",
      },
      items: rawApi as SidebarsConfig[],
    },
  ],
};

export default sidebars;
