import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/xenforo-api",
    },
    {
      type: "category",
      label: "Alerts",
      link: {
        type: "doc",
        id: "api/alerts",
      },
      items: [
        {
          type: "doc",
          id: "api/get-alerts",
          label: "Get a list of user alerts",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-alerts",
          label: "Send an alert to the specified user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-alerts-mark-all",
          label: "Mark all alerts as read or viewed",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-alerts-id",
          label: "Get information about the specified alert",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-alerts-id-mark",
          label: "Mark the alert as viewed, read, or unread",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Attachments",
      link: {
        type: "doc",
        id: "api/attachments",
      },
      items: [
        {
          type: "doc",
          id: "api/get-attachments",
          label: "Get attachments by API attachment key",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-attachments",
          label: "Upload an attachment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-attachments-new-key",
          label: "Create an attachment key",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-attachments-id",
          label: "Get information about the specified attachment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-attachments-id",
          label: "Delete the specified attachment",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-attachments-id-data",
          label: "Get the data that makes up the specified attachment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-attachments-id-retina-thumbnail",
          label: "Get an attachment thumbnail URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-attachments-id-thumbnail",
          label: "Get an attachment thumbnail URL",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Auth",
      link: {
        type: "doc",
        id: "api/auth",
      },
      items: [
        {
          type: "doc",
          id: "api/post-auth",
          label: "Test a login and password for validity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-auth-from-session",
          label: "Look up an active user from session data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-auth-login-token",
          label: "Generate a login token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Conversations",
      link: {
        type: "doc",
        id: "api/conversations",
      },
      items: [
        {
          type: "doc",
          id: "api/post-conversation-messages",
          label: "Reply to a conversation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-conversation-messages-id",
          label: "Get the specified conversation message",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-conversation-messages-id",
          label: "Update the specified conversation message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-conversation-messages-id-react",
          label: "React to the specified conversation message",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-conversations",
          label: "Get a list of user conversations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-conversations",
          label: "Create a conversation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-conversations-id",
          label: "Get information about the specified conversation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-conversations-id",
          label: "Update the specified conversation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-conversations-id",
          label: "Delete a conversation from the user list",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-conversations-id-invite",
          label: "Invite the specified users to this conversation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-conversations-id-labels",
          label: "Set labels on the specified conversation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-conversations-id-mark-read",
          label: "Mark a conversation as read",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-conversations-id-mark-unread",
          label: "Mark the conversation as unread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-conversations-id-messages",
          label: "Get a page of messages in the specified conversation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-conversations-id-star",
          label: "Set the star status of the specified conversation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Featured content",
      link: {
        type: "doc",
        id: "api/featured-content",
      },
      items: [
        {
          type: "doc",
          id: "api/get-featured",
          label: "Get a list of featured content",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Forums",
      link: {
        type: "doc",
        id: "api/forums",
      },
      items: [
        {
          type: "doc",
          id: "api/get-forums-id",
          label: "Get information about the specified forum",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-forums-id-mark-read",
          label: "Mark a forum as read",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-forums-id-threads",
          label: "Get a page of threads from the specified forum",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Index",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [
        {
          type: "doc",
          id: "api/get-index",
          label: "Get site and API information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Me",
      link: {
        type: "doc",
        id: "api/me",
      },
      items: [
        {
          type: "doc",
          id: "api/get-me",
          label: "Get information about the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-me",
          label: "Update information about the current user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-me-avatar",
          label: "Update the current user avatar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-me-avatar",
          label: "Delete the current user avatar",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-me-email",
          label: "Update the current user email address",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-me-password",
          label: "Update the current user password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Media",
      link: {
        type: "doc",
        id: "api/media",
      },
      items: [
        {
          type: "doc",
          id: "api/get-media",
          label: "Get a list of media items",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media",
          label: "Create a media item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-media-id",
          label: "Get information about the specified media item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-id",
          label: "Update the specified media item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-media-id",
          label: "Delete the specified media item",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-media-id-comments",
          label: "Get a page of comments on the specified media item",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-media-id-data",
          label: "Get a media item file",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-id-feature",
          label: "Set feature state for the specified media",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-media-id-react",
          label: "React to the specified media item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-media-id-unfeature",
          label: "Delete the feature for the specified media",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Media albums",
      link: {
        type: "doc",
        id: "api/media-albums",
      },
      items: [
        {
          type: "doc",
          id: "api/get-media-albums",
          label: "Get a list of albums",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-albums",
          label: "Create an album",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-media-albums-id",
          label: "Get information about the specified album",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-albums-id",
          label: "Update the specified album",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-media-albums-id",
          label: "Delete the specified album",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-media-albums-id-comments",
          label: "Get a page of comments on the specified album",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-media-albums-id-media",
          label: "Get a page of media from the specified album",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-albums-id-react",
          label: "React to the specified album",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Media categories",
      link: {
        type: "doc",
        id: "api/media-categories",
      },
      items: [
        {
          type: "doc",
          id: "api/get-media-categories",
          label: "Get the media category tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-categories",
          label: "Create a media category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-media-categories-flattened",
          label: "Get a flattened list of media categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-media-categories-id",
          label: "Get information about the specified media category",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-categories-id",
          label: "Update the specified media category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-media-categories-id",
          label: "Delete the specified category",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-media-categories-id-content",
          label: "Get a page of content from the specified category",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Media comments",
      link: {
        type: "doc",
        id: "api/media-comments",
      },
      items: [
        {
          type: "doc",
          id: "api/get-media-comments",
          label: "Get a list of latest comments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-comments",
          label: "Create a comment on an album or media item",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-media-comments-id",
          label: "Get information about the specified comment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-media-comments-id",
          label: "Update the specified comment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-media-comments-id",
          label: "Delete the specified comment",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-media-comments-id-react",
          label: "React to the specified comment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Nodes",
      link: {
        type: "doc",
        id: "api/nodes",
      },
      items: [
        {
          type: "doc",
          id: "api/get-nodes",
          label: "Get the node tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-nodes",
          label: "Create a new node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-nodes-flattened",
          label: "Get a flattened node tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-nodes-id",
          label: "Get information about the specified node",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-nodes-id",
          label: "Update the specified node",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-nodes-id",
          label: "Delete the specified node",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "OAuth2",
      link: {
        type: "doc",
        id: "api/o-auth-2",
      },
      items: [
        {
          type: "doc",
          id: "api/post-oauth-2-introspect",
          label: "Introspect an OAuth token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-oauth-2-revoke",
          label: "Revoke an access token or refresh token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-oauth-2-token",
          label: "Get information about an OAuth token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-oauth-2-token",
          label: "Exchange a token grant",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Posts",
      link: {
        type: "doc",
        id: "api/posts",
      },
      items: [
        {
          type: "doc",
          id: "api/post-posts",
          label: "Add a new reply to a thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-posts-id",
          label: "Get information about the specified post",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-posts-id",
          label: "Update the specified post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-posts-id",
          label: "Delete the specified post",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-posts-id-mark-solution",
          label: "Toggle a post as the thread solution",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-posts-id-react",
          label: "React to the specified post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-posts-id-vote",
          label: "Vote on the specified post",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Profile posts",
      link: {
        type: "doc",
        id: "api/profile-posts",
      },
      items: [
        {
          type: "doc",
          id: "api/post-profile-post-comments",
          label: "Create a new profile post comment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile-post-comments-id",
          label: "Get a profile post comment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-profile-post-comments-id",
          label: "Update the specified profile post comment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-profile-post-comments-id",
          label: "Delete the specified profile post comment",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-profile-post-comments-id-react",
          label: "React to the specified profile post comment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-profile-posts",
          label: "Create a new profile post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile-posts-id",
          label: "Get information about the specified profile post",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-profile-posts-id",
          label: "Update the specified profile post",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-profile-posts-id",
          label: "Delete the specified profile post",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-profile-posts-id-comments",
          label: "Get a page of comments on the specified profile post",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-profile-posts-id-react",
          label: "React to the specified profile post",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Resource categories",
      link: {
        type: "doc",
        id: "api/resource-categories",
      },
      items: [
        {
          type: "doc",
          id: "api/get-resource-categories",
          label: "Get the resource category tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resource-categories",
          label: "Create a resource category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resource-categories-flattened",
          label: "Get a flattened list of resource categories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-resource-categories-id",
          label: "Get information about the specified resource category",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resource-categories-id",
          label: "Update the specified resource category",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-resource-categories-id",
          label: "Delete the specified category",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-resource-categories-id-resources",
          label: "Get a page of resources from the specified category",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Resource reviews",
      link: {
        type: "doc",
        id: "api/resource-reviews",
      },
      items: [
        {
          type: "doc",
          id: "api/get-resource-reviews",
          label: "Get a list of latest resource reviews",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resource-reviews",
          label: "Create a review or rating for a resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resource-reviews-id",
          label: "Get information about the specified review",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-resource-reviews-id",
          label: "Delete the specified review",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-resource-reviews-id-author-reply",
          label: "Add or update an author reply",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-resource-reviews-id-author-reply",
          label: "Remove the author reply from the specified review",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Resource updates",
      link: {
        type: "doc",
        id: "api/resource-updates",
      },
      items: [
        {
          type: "doc",
          id: "api/post-resource-updates",
          label: "Create a resource update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resource-updates-id",
          label: "Get information about the specified resource update",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resource-updates-id",
          label: "Update the specified resource update",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-resource-updates-id",
          label: "Delete the specified resource update",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Resource versions",
      link: {
        type: "doc",
        id: "api/resource-versions",
      },
      items: [
        {
          type: "doc",
          id: "api/post-resource-versions",
          label: "Create a new version of a resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resource-versions-id",
          label: "Get information about the specified resource version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-resource-versions-id",
          label: "Delete the specified resource version",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-resource-versions-id-download",
          label: "Download a resource version file",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      link: {
        type: "doc",
        id: "api/resources",
      },
      items: [
        {
          type: "doc",
          id: "api/get-resources",
          label: "Get a list of resources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resources",
          label: "Create a resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resources-id",
          label: "Get information about the specified resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resources-id",
          label: "Update the specified resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-resources-id",
          label: "Delete the specified resource",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-resources-id-feature",
          label: "Set feature state for the specified resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resources-id-reviews",
          label: "Get a page of reviews for the specified resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-resources-id-unfeature",
          label: "Delete the feature for the specified resource",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-resources-id-updates",
          label: "Get a page of updates for the specified resource",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-resources-id-versions",
          label: "Get a list of versions for the specified resource",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Search",
      link: {
        type: "doc",
        id: "api/search",
      },
      items: [
        {
          type: "doc",
          id: "api/post-search",
          label: "Create a new search",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-search-member",
          label: "Retrieve search results for a specific member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-search-id",
          label: "Retrieve search results for a given search",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-search-id-older",
          label: "Retrieve older search results for a given search",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Search forums",
      link: {
        type: "doc",
        id: "api/search-forums",
      },
      items: [
        {
          type: "doc",
          id: "api/get-search-forums-id",
          label: "Get information about the specified search forum",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-search-forums-id-threads",
          label: "Get a page of threads from the specified search forum",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Stats",
      link: {
        type: "doc",
        id: "api/stats",
      },
      items: [
        {
          type: "doc",
          id: "api/get-stats",
          label: "Get site statistics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Threads",
      link: {
        type: "doc",
        id: "api/threads",
      },
      items: [
        {
          type: "doc",
          id: "api/get-threads",
          label: "Get a list of threads",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-threads",
          label: "Create a thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-threads-id",
          label: "Get information about the specified thread",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-threads-id",
          label: "Update the specified thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-threads-id",
          label: "Delete the specified thread",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-threads-id-change-type",
          label: "Convert a thread to the specified type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-threads-id-feature",
          label: "Set feature state for the specified thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-threads-id-mark-read",
          label: "Mark a thread as read",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-threads-id-move",
          label: "Move the specified thread to a different forum",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-threads-id-posts",
          label: "Get a page of posts in the specified thread",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-threads-id-unfeature",
          label: "Delete the feature for the specified thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/post-threads-id-vote",
          label: "Vote on the specified thread",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      link: {
        type: "doc",
        id: "api/users",
      },
      items: [
        {
          type: "doc",
          id: "api/get-users",
          label: "Get a list of users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-users",
          label: "Create a user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-users-find-email",
          label: "Find users by email",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-users-find-name",
          label: "Find users by a prefix of their user name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-users-id",
          label: "Get information about the specified user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/post-users-id",
          label: "Update an existing user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-users-id",
          label: "Delete the specified user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/post-users-id-avatar",
          label: "Update the specified user avatar",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-users-id-avatar",
          label: "Delete the specified user avatar",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-users-id-profile-posts",
          label: "Get a page of user profile posts",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "oEmbed",
      link: {
        type: "doc",
        id: "api/o-embed",
      },
      items: [
        {
          type: "doc",
          id: "api/get-oembed",
          label: "Get oEmbed data for the given URL",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Schemas",
      items: [
        {
          type: "doc",
          id: "api/schemas/attachment",
          label: "Attachment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/conversation",
          label: "Conversation",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/conversationmessage",
          label: "ConversationMessage",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/featuredcontent",
          label: "FeaturedContent",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/forum",
          label: "Forum",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/linkforum",
          label: "LinkForum",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/node",
          label: "Node",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/page",
          label: "Page",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/pagination",
          label: "Pagination",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/poll",
          label: "Poll",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/post",
          label: "Post",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profilepost",
          label: "ProfilePost",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/profilepostcomment",
          label: "ProfilePostComment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/search",
          label: "Search",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/thread",
          label: "Thread",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/threadfield",
          label: "ThreadField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/threadprefix",
          label: "ThreadPrefix",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/user",
          label: "User",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/useralert",
          label: "UserAlert",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/userfield",
          label: "UserField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfmg-album",
          label: "XFMG_Album",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfmg-category",
          label: "XFMG_Category",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfmg-comment",
          label: "XFMG_Comment",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfmg-mediafield",
          label: "XFMG_MediaField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfmg-mediaitem",
          label: "XFMG_MediaItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-category",
          label: "XFRM_Category",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourcefield",
          label: "XFRM_ResourceField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourceitem",
          label: "XFRM_ResourceItem",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourceprefix",
          label: "XFRM_ResourcePrefix",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourcerating",
          label: "XFRM_ResourceRating",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourcereviewfield",
          label: "XFRM_ResourceReviewField",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourceupdate",
          label: "XFRM_ResourceUpdate",
          className: "schema",
        },
        {
          type: "doc",
          id: "api/schemas/xfrm-resourceversion",
          label: "XFRM_ResourceVersion",
          className: "schema",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
