name: Spell check

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "cspell.json"
      - ".github/workflows/spellcheck.yml"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**/*.md"
      - "docs/**/*.mdx"
      - "README.md"
      - "CONTRIBUTING.md"
      - "LICENSE"
      - "cspell.json"
      - ".github/workflows/spellcheck.yml"

concurrency:
  group: "${{ github.workflow }}@${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

permissions: {}

jobs:
  spellcheck:
    name: Spell check
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # related to postmanlabs/postman-code-generators#792
      - name: Uninstall yarn
        run: sudo rm -f $(which yarn)

      - name: Set up pnpm and Node.js
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true
          require-lockfile: true

      - name: Run spell check
        run: pnpm spellcheck
